name: badges
on:
  pull_request:
    branches: [main]
    # update README badge only if the README file changes
    # or if the package.json file changes, or this file changes
    paths:
      - README.md
      - package.json
      - .github/workflows/badges.yml
  schedule:
    # update badges every night
    # because we have a few badges that are linked
    # to the external repositories
    - cron: '0 3 * * *'

  workflow_dispatch:

jobs:
  badges:
    name: Badges
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        # heck out the actual HEAD commit in the pull request.
        # so we can find the branch refernce with github.head_ref later
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Update version badges 🏷
        run:
          npx -p dependency-version-badge update-badge react react-scripts
          cypress jest eslint prettier cypress jest typescript

      - name: Commit any changed files 💾
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges
          branch: ${{ github.head_ref }}
          file_pattern: README.md
          push_options: '--force'
          skip_fetch: true
